### ISSUE TITLE
does jQuery is really needed?

### ISSUE THREAD

**Issue by ovidijusr** [AmanAgarwal041/Toast#1]
There are a lot of toast libraries with a lot of different functions. Wouldn't it be nice to make one which doesn't require jQuery so people could use it as a component for other frameworks?

**Comment by AmanAgarwal041** [comment]
yes. Will publish a pure javascript version soon.

**Comment by AmanAgarwal041** [comment]
@ovidijusr I have added the javascript version. I hope it helps.
